import { useState } from "react";

const tiers = [
  "T1 - Omniversal",
  "T2 - Beyond Multiversal",
  "T3 - High Multiversal",
  "T4 - Multiversal+",
  "T5 - Multiversal",
  "T6 - Universal+",
  "T7 - Universal",
  "T8 - Large Planetary to Galaxy Level",
  "T9 - Star System Level",
  "T10 - Planetary",
  "T11 - Moon Level",
  "T12 - Continent Level",
  "T13 - Country Level",
  "T14 - City Level",
  "T15 - Mountain Level",
  "T16 - Building Level",
  "T17 - Wall Level",
  "T18 - Street Level",
  "T19 - Peak Human",
  "T20 - Regular Human" 
];


const characters = [
  { id: 1, name: "Rimuru Tempest", universe: "Slime Datta Ken", tier: "T5 - Multiversal" },
  { id: 2, name: "Diablo", universe: "Slime Datta Ken", tier: "T6 - Universal+" },
  { id: 3, name: "Shion", universe: "Slime Datta Ken", tier: "T8 - Large Planetary to Galaxy Level" },
  { id: 4, name: "Benimaru", universe: "Slime Datta Ken", tier: "T9 - Star System Level" },
  { id: 5, name: "Shuna", universe: "Slime Datta Ken", tier: "T14 - City Level" },
  { id: 6, name: "Souei", universe: "Slime Datta Ken", tier: "T8 - Large Planetary to Galaxy Level" },
  { id: 7, name: "Hakurou", universe: "Slime Datta Ken", tier: "T15 - Mountain Level" },
  { id: 8, name: "Ranga", universe: "Slime Datta Ken", tier: "T12 - Continent Level" },
  { id: 9, name: "Veldora Tempest", universe: "Slime Datta Ken", tier: "T4 - Multiversal+" },
  { id: 10, name: "Milim Nava", universe: "Slime Datta Ken", tier: "T3 - High Multiversal" },
  { id: 11, name: "Frey", universe: "Slime Datta Ken", tier: "T13 - Country Level" },
  { id: 12, name: "Gabil", universe: "Slime Datta Ken", tier: "T17 - Wall Level" },
  { id: 13, name: "Iroha", universe: "Slime Datta Ken", tier: "T15 - Mountain Level" },
  { id: 14, name: "Rigurdo", universe: "Slime Datta Ken", tier: "T18 - Street Level" },
  { id: 15, name: "Gobta", universe: "Slime Datta Ken", tier: "T20 - Regular Human" },
  { id: 16, name: "Ramiris", universe: "Slime Datta Ken", tier: "T7 - Universal" },
  { id: 17, name: "Geld", universe: "Slime Datta Ken", tier: "T6 - Universal+" },
  { id: 18, name: "Carrion", universe: "Slime Datta Ken", tier: "T11 - Moon Level" },
  { id: 19, name: "Clayman", universe: "Slime Datta Ken", tier: "T5 - Multiversal" },
  { id: 20, name: "Treyni", universe: "Slime Datta Ken", tier: "T14 - City Level" },
  { id: 21, name: "Hinata Sakaguchi", universe: "Slime Datta Ken", tier: "T9 - Star System Level" },
  { id: 22, name: "Kurobe", universe: "Slime Datta Ken", tier: "T16 - Building Level" },
  { id: 23, name: "Luminous Valentine", universe: "Slime Datta Ken", tier: "T13 - Country Level" },
  { id: 24, name: "Towa", universe: "Slime Datta Ken", tier: "T6 - Universal+" },
  { id: 25, name: "Kaguya Ōtsutsuki", universe: "Naruto", tier: "T2 - Beyond Multiversal" },
  { id: 26, name: "Hagoromo Ōtsutsuki (Sage of Six Paths)", universe: "Naruto", tier: "T3 - High Multiversal" },
  { id: 27, name: "Hamura Ōtsutsuki", universe: "Naruto", tier: "T4 - Multiversal+" },
  { id: 28, name: "Naruto Uzumaki (Sage Mode + Kurama)", universe: "Naruto", tier: "T5 - Multiversal" },
  { id: 29, name: "Sasuke Uchiha (Rinnegan + Eternal Mangekyo)", universe: "Naruto", tier: "T5 - Multiversal" },
  { id: 30, name: "Madara Uchiha (Ten Tails Jinchuriki)", universe: "Naruto", tier: "T5 - Multiversal" },
  { id: 31, name: "Hashirama Senju", universe: "Naruto", tier: "T7 - Universal" },
  { id: 32, name: "Obito Uchiha (Ten Tails Jinchuriki)", universe: "Naruto", tier: "T5 - Multiversal" },
  { id: 33, name: "Kakashi Hatake (Double Mangekyo Sharingan)", universe: "Naruto", tier: "T9 - Star System Level" },
  { id: 34, name: "Might Guy (Eighth Gate)", universe: "Naruto", tier: "T8 - Large Planetary to Galaxy Level" },
  { id: 35, name: "Minato Namikaze (Fourth Hokage)", universe: "Naruto", tier: "T10 - Planetary" },
  { id: 36, name: "Itachi Uchiha", universe: "Naruto", tier: "T11 - Moon Level" },
  { id: 37, name: "Tsunade Senju", universe: "Naruto", tier: "T14 - City Level" },
  { id: 38, name: "Gaara (Kazekage)", universe: "Naruto", tier: "T13 - Country Level" },
  { id: 39, name: "Shikamaru Nara", universe: "Naruto", tier: "T16 - Building Level" },
  { id: 40, name: "Neji Hyuga", universe: "Naruto", tier: "T15 - Mountain Level" },
  { id: 41, name: "Rock Lee (Without Eight Gates)", universe: "Naruto", tier: "T19 - Peak Human" },
  { id: 42, name: "Hinata Hyuga", universe: "Naruto", tier: "T18 - Street Level" },
  { id: 43, name: "Killer Bee", universe: "Naruto", tier: "T12 - Continent Level" },
  { id: 44, name: "Jiraiya", universe: "Naruto", tier: "T11 - Moon Level" },
  { id: 45, name: "Orochimaru", universe: "Naruto", tier: "T12 - Continent Level" },
  { id: 46, name: "Sai", universe: "Naruto", tier: "T16 - Building Level" },
  { id: 47, name: "Kurenai Yuhi", universe: "Naruto", tier: "T18 - Street Level" },
  { id: 48, name: "Asuma Sarutobi", universe: "Naruto", tier: "T18 - Street Level" },
  { id: 49, name: "Shino Aburame", universe: "Naruto", tier: "T18 - Street Level" },
  { id: 50, name: "Konohamaru Sarutobi", universe: "Naruto", tier: "T19 - Peak Human" },
  { id: 51, name: "Tenten", universe: "Naruto", tier: "T19 - Peak Human" },
  { id: 52, name: "Kiba Inuzuka", universe: "Naruto", tier: "T18 - Street Level" },
  { id: 53, name: "Shisui Uchiha", universe: "Naruto", tier: "T10 - Planetary" },
  { id: 54, name: "Obito Uchiha (Masked)", universe: "Naruto", tier: "T5 - Multiversal" },
  { id: 55, name: "Nagato (Pain)", universe: "Naruto", tier: "T7 - Universal" },
  { id: 56, name: "Killer Bee (Jinchuriki)", universe: "Naruto", tier: "T11 - Moon Level" },
  { id: 57, name: "Hiruzen Sarutobi (Third Hokage)", universe: "Naruto", tier: "T12 - Continent Level" },
  { id: 58, name: "Danzo Shimura", universe: "Naruto", tier: "T13 - Country Level" },
  { id: 59, name: "Kakuzu", universe: "Naruto", tier: "T13 - Country Level" },
  { id: 60, name: "Zabuza Momochi", universe: "Naruto", tier: "T17 - Wall Level" },
  { id: 61, name: "Haku", universe: "Naruto", tier: "T18 - Street Level" },
  { id: 62, name: "Kimimaro", universe: "Naruto", tier: "T14 - City Level" },
  { id: 63, name: "Yamato", universe: "Naruto", tier: "T14 - City Level" },
  { id: 64, name: "Sai (Anbu)", universe: "Naruto", tier: "T15 - Mountain Level" },
  { id: 65, name: "Kurenai Yuhi (Anbu)", universe: "Naruto", tier: "T16 - Building Level" },
  { id: 66, name: "Ino Yamanaka", universe: "Naruto", tier: "T18 - Street Level" },
  { id: 67, name: "Choji Akimichi", universe: "Naruto", tier: "T17 - Wall Level" },
  { id: 68, name: "Shikadai Nara", universe: "Naruto", tier: "T18 - Street Level" },
  { id: 69, name: "Boruto Uzumaki", universe: "Naruto", tier: "T17 - Wall Level" },
  { id: 70, name: "Sarada Uchiha", universe: "Naruto", tier: "T18 - Street Level" },
  { id: 71, name: "Gol D. Roger", universe: "One Piece", tier: "T7 - Universal" },
  { id: 72, name: "Whitebeard (Edward Newgate)", universe: "One Piece", tier: "T7 - Universal" },
  { id: 73, name: "Kaido", universe: "One Piece", tier: "T7 - Universal" },
  { id: 74, name: "Big Mom (Charlotte Linlin)", universe: "One Piece", tier: "T7 - Universal" },
  { id: 75, name: "Monkey D. Luffy (Gear 5)", universe: "One Piece", tier: "T9 - Star System Level" },
  { id: 76, name: "Shanks", universe: "One Piece", tier: "T8 - Large Planetary to Galaxy Level" },
  { id: 77, name: "Blackbeard (Marshall D. Teach)", universe: "One Piece", tier: "T7 - Universal" },
  { id: 78, name: "Admiral Akainu (Sakazuki)", universe: "One Piece", tier: "T8 - Large Planetary to Galaxy Level" },
  { id: 79, name: "Admiral Aokiji (Kuzan)", universe: "One Piece", tier: "T8 - Large Planetary to Galaxy Level" },
  { id: 80, name: "Admiral Kizaru (Borsalino)", universe: "One Piece", tier: "T8 - Large Planetary to Galaxy Level" },
  { id: 81, name: "Admiral Fujitora (Issho)", universe: "One Piece", tier: "T8 - Large Planetary to Galaxy Level" },
  { id: 82, name: "Dracule Mihawk", universe: "One Piece", tier: "T10 - Planetary" },
  { id: 83, name: "Trafalgar D. Water Law", universe: "One Piece", tier: "T11 - Moon Level" },
  { id: 84, name: "Eustass Kid", universe: "One Piece", tier: "T11 - Moon Level" },
  { id: 85, name: "Portgas D. Ace", universe: "One Piece", tier: "T12 - Continent Level" },
  { id: 86, name: "Sabo", universe: "One Piece", tier: "T12 - Continent Level" },
  { id: 87, name: "Roronoa Zoro", universe: "One Piece", tier: "T11 - Moon Level" },
  { id: 88, name: "Jinbe", universe: "One Piece", tier: "T13 - Country Level" },
  { id: 89, name: "Franky", universe: "One Piece", tier: "T15 - Mountain Level" },
  { id: 90, name: "Brook", universe: "One Piece", tier: "T17 - Wall Level" },
  { id: 91, name: "Nico Robin", universe: "One Piece", tier: "T16 - Building Level" },
  { id: 92, name: "Usopp", universe: "One Piece", tier: "T18 - Street Level" },
  { id: 93, name: "Sanji", universe: "One Piece", tier: "T14 - City Level" },
  { id: 94, name: "Chopper", universe: "One Piece", tier: "T18 - Street Level" },
  { id: 95, name: "Nami", universe: "One Piece", tier: "T18 - Street Level" },
  { id: 96, name: "Vinsmoke Judge", universe: "One Piece", tier: "T13 - Country Level" },
  { id: 97, name: "Vinsmoke Reiju", universe: "One Piece", tier: "T15 - Mountain Level" },
  { id: 98, name: "Charlotte Katakuri", universe: "One Piece", tier: "T11 - Moon Level" },
  { id: 99, name: "Charlotte Smoothie", universe: "One Piece", tier: "T13 - Country Level" },
  { id: 100, name: "Caesar Clown", universe: "One Piece", tier: "T14 - City Level" },
  { id: 101, name: "Donquixote Doflamingo", universe: "One Piece", tier: "T11 - Moon Level" },
  { id: 102, name: "Bartholomew Kuma", universe: "One Piece", tier: "T10 - Planetary" },
  { id: 103, name: "Kizaru (Borsalino)", universe: "One Piece", tier: "T8 - Large Planetary to Galaxy Level" },
  { id: 104, name: "Coby", universe: "One Piece", tier: "T15 - Mountain Level" },
  { id: 105, name: "Magellan", universe: "One Piece", tier: "T14 - City Level" },
  { id: 106, name: "Sentomaru", universe: "One Piece", tier: "T16 - Building Level" },
  { id: 107, name: "Killer", universe: "One Piece", tier: "T17 - Wall Level" },
  { id: 108, name: "Bon Clay (Mr. 2)", universe: "One Piece", tier: "T18 - Street Level" },
  { id: 109, name: "Franky (Battle Franky)", universe: "One Piece", tier: "T15 - Mountain Level" },
  { id: 110, name: "Brook (Soul King)", universe: "One Piece", tier: "T17 - Wall Level" },
  { id: 111, name: "Jozu", universe: "One Piece", tier: "T12 - Continent Level" },
  { id: 112, name: "Vista", universe: "One Piece", tier: "T13 - Country Level" },
  { id: 113, name: "Fujitora (Issho)", universe: "One Piece", tier: "T8 - Large Planetary to Galaxy Level" },
  { id: 114, name: "Kuma (Pacifista)", universe: "One Piece", tier: "T14 - City Level" },
  { id: 115, name: "Jewelry Bonney", universe: "One Piece", tier: "T17 - Wall Level" },
  { id: 116, name: "Meruem", universe: "Hunter x Hunter", tier: "T6 - Universal+" },
  { id: 117, name: "Netero", universe: "Hunter x Hunter", tier: "T8 - Large Planetary to Galaxy Level" },
  { id: 118, name: "Ging Freecss", universe: "Hunter x Hunter", tier: "T7 - Universal" },
  { id: 119, name: "Killua Zoldyck", universe: "Hunter x Hunter", tier: "T14 - City Level" },
  { id: 120, name: "Gon Freecss (Adult)", universe: "Hunter x Hunter", tier: "T7 - Universal" },
  { id: 121, name: "Hisoka Morow", universe: "Hunter x Hunter", tier: "T12 - Continent Level" },
  { id: 122, name: "Chrollo Lucilfer", universe: "Hunter x Hunter", tier: "T12 - Continent Level" },
  { id: 123, name: "Feitan Portor", universe: "Hunter x Hunter", tier: "T14 - City Level" },
  { id: 124, name: "Shalnark", universe: "Hunter x Hunter", tier: "T15 - Mountain Level" },
  { id: 125, name: "Pakunoda", universe: "Hunter x Hunter", tier: "T16 - Building Level" },
  { id: 126, name: "Illumi Zoldyck", universe: "Hunter x Hunter", tier: "T13 - Country Level" },
  { id: 127, name: "Leorio Paradinight", universe: "Hunter x Hunter", tier: "T18 - Street Level" },
  { id: 128, name: "Kurapika", universe: "Hunter x Hunter", tier: "T13 - Country Level" },
  { id: 129, name: "Biscuit Krueger", universe: "Hunter x Hunter", tier: "T15 - Mountain Level" },
  { id: 130, name: "Zeno Zoldyck", universe: "Hunter x Hunter", tier: "T9 - Star System Level" },
  { id: 131, name: "Silva Zoldyck", universe: "Hunter x Hunter", tier: "T9 - Star System Level" },
  { id: 132, name: "Menthuthuyoupi", universe: "Hunter x Hunter", tier: "T11 - Moon Level" },
  { id: 133, name: "Shaiapouf", universe: "Hunter x Hunter", tier: "T11 - Moon Level" },
  { id: 134, name: "Genthru", universe: "Hunter x Hunter", tier: "T16 - Building Level" },
  { id: 135, name: "Phinks", universe: "Hunter x Hunter", tier: "T15 - Mountain Level" },
  { id: 136, name: "Uvogin", universe: "Hunter x Hunter", tier: "T14 - City Level" },
  { id: 137, name: "Pakunoda", universe: "Hunter x Hunter", tier: "T16 - Building Level" },
  { id: 138, name: "Knuckle Bine", universe: "Hunter x Hunter", tier: "T15 - Mountain Level" },
  { id: 139, name: "Shoot McMahon", universe: "Hunter x Hunter", tier: "T15 - Mountain Level" },
  { id: 140, name: "Morel Mackernasey", universe: "Hunter x Hunter", tier: "T14 - City Level" },
  { id: 141, name: "Machi Komacine", universe: "Hunter x Hunter", tier: "T16 - Building Level" },
  { id: 142, name: "Franklin Bordeau", universe: "Hunter x Hunter", tier: "T15 - Mountain Level" },
  { id: 143, name: "Kortopi", universe: "Hunter x Hunter", tier: "T17 - Wall Level" },
  { id: 144, name: "Shizuku Murasaki", universe: "Hunter x Hunter", tier: "T17 - Wall Level" },
  { id: 145, name: "Neferpitou", universe: "Hunter x Hunter", tier: "T10 - Planetary" },
  { id: 146, name: "Knov", universe: "Hunter x Hunter", tier: "T14 - City Level" },
  { id: 147, name: "Palm Siberia", universe: "Hunter x Hunter", tier: "T13 - Country Level" },
  { id: 148, name: "Ikalgo", universe: "Hunter x Hunter", tier: "T16 - Building Level" },
  { id: 149, name: "Gon Freecss (Child)", universe: "Hunter x Hunter", tier: "T17 - Wall Level" },
  { id: 150, name: "Killua Zoldyck (Child)", universe: "Hunter x Hunter", tier: "T17 - Wall Level" },
  { id: 151, name: "Komugi", universe: "Hunter x Hunter", tier: "T20 - Regular Human" },
  { id: 152, name: "Zushi", universe: "Hunter x Hunter", tier: "T18 - Street Level" },
  { id: 153, name: "Colt", universe: "Hunter x Hunter", tier: "T15 - Mountain Level" },
  { id: 154, name: "Welfin", universe: "Hunter x Hunter", tier: "T16 - Building Level" },
  { id: 155, name: "Knov", universe: "Hunter x Hunter", tier: "T14 - City Level" },
  { id: 156, name: "Kite", universe: "Hunter x Hunter", tier: "T13 - Country Level" },
  { id: 157, name: "Zagred", universe: "Hunter x Hunter", tier: "T5 - Multiversal" },
  { id: 158, name: "Beyond Netero", universe: "Hunter x Hunter", tier: "T6 - Universal+" },
  { id: 159, name: "Cheadle Yorkshire", universe: "Hunter x Hunter", tier: "T15 - Mountain Level" },
  { id: 160, name: "Meleoron", universe: "Hunter x Hunter", tier: "T16 - Building Level" },
  { id: 161, name: "Knuckle Bine", universe: "Hunter x Hunter", tier: "T15 - Mountain Level" },
  { id: 162, name: "Pariston Hill", universe: "Hunter x Hunter", tier: "T16 - Building Level" },
  { id: 163, name: "Yami Sukehiro", universe: "Black Clover", tier: "T8 - Large Planetary to Galaxy Level" },
  { id: 164, name: "Asta (Devil Form)", universe: "Black Clover", tier: "T7 - Universal" },
  { id: 165, name: "Noelle Silva", universe: "Black Clover", tier: "T13 - Country Level" },
  { id: 166, name: "Luck Voltia", universe: "Black Clover", tier: "T14 - City Level" },
  { id: 167, name: "Finral Roulacase", universe: "Black Clover", tier: "T16 - Building Level" },
  { id: 168, name: "Charmy Pappitson", universe: "Black Clover", tier: "T18 - Street Level" },
  { id: 169, name: "Gauche Adlai", universe: "Black Clover", tier: "T15 - Mountain Level" },
  { id: 170, name: "Mimosa Vermillion", universe: "Black Clover", tier: "T17 - Wall Level" },
  { id: 171, name: "Magna Swing", universe: "Black Clover", tier: "T16 - Building Level" },
  { id: 172, name: "Gordon Agrippa", universe: "Black Clover", tier: "T20 - Regular Human" },
  { id: 173, name: "Zora Ideale", universe: "Black Clover", tier: "T15 - Mountain Level" },
  { id: 174, name: "Vanessa Enoteca", universe: "Black Clover", tier: "T13 - Country Level" },
  { id: 175, name: "Yuno", universe: "Black Clover", tier: "T6 - Universal+" },
  { id: 176, name: "William Vangeance", universe: "Black Clover", tier: "T5 - Multiversal" },
  { id: 177, name: "Mereoleona Vermillion", universe: "Black Clover", tier: "T9 - Star System Level" },
  { id: 178, name: "Fuegoleon Vermillion", universe: "Black Clover", tier: "T10 - Planetary" },
  { id: 179, name: "Secre Swallowtail", universe: "Black Clover", tier: "T15 - Mountain Level" },
  { id: 180, name: "Nozel Silva", universe: "Black Clover", tier: "T11 - Moon Level" },
  { id: 181, name: "Rill Boismortier", universe: "Black Clover", tier: "T16 - Building Level" },
  { id: 182, name: "Licht", universe: "Black Clover", tier: "T4 - Multiversal+" },
  { id: 183, name: "Patolli", universe: "Black Clover", tier: "T4 - Multiversal+" },
  { id: 184, name: "Fana", universe: "Black Clover", tier: "T5 - Multiversal" },
  { id: 185, name: "Rades Spirito", universe: "Black Clover", tier: "T12 - Continent Level" },
  { id: 186, name: "Langris Vaude", universe: "Black Clover", tier: "T7 - Universal" },
  { id: 187, name: "Zagred", universe: "Black Clover", tier: "T3 - High Multiversal" },
  { id: 188, name: "Lolopechka", universe: "Black Clover", tier: "T13 - Country Level" },
  { id: 189, name: "Dorothy Unsworth", universe: "Black Clover", tier: "T10 - Planetary" },
  { id: 190, name: "Ruben", universe: "Black Clover", tier: "T19 - Peak Human" },
  { id: 191, name: "Mars", universe: "Black Clover", tier: "T14 - City Level" },
  { id: 192, name: "Kaiser Granvorka", universe: "Black Clover", tier: "T13 - Country Level" },
  { id: 193, name: "Eren Yeager (Founding Titan)", universe: "Attack on Titan", tier: "T4 - Multiversal+" },
  { id: 194, name: "Armin Arlert (Colossal Titan)", universe: "Attack on Titan", tier: "T10 - Planetary" },
  { id: 195, name: "Reiner Braun (Armored Titan)", universe: "Attack on Titan", tier: "T12 - Continent Level" },
  { id: 196, name: "Annie Leonhart (Female Titan)", universe: "Attack on Titan", tier: "T12 - Continent Level" },
  { id: 197, name: "Zeke Yeager (Beast Titan)", universe: "Attack on Titan", tier: "T11 - Moon Level" },
  { id: 198, name: "Levi Ackerman", universe: "Attack on Titan", tier: "T16 - Building Level" },
  { id: 199, name: "Mikasa Ackerman", universe: "Attack on Titan", tier: "T15 - Mountain Level" },
  { id: 200, name: "Historia Reiss", universe: "Attack on Titan", tier: "T18 - Street Level" },
  { id: 201, name: "Porco Galliard (Jaw Titan)", universe: "Attack on Titan", tier: "T14 - City Level" },
  { id: 202, name: "Pieck Finger (Cart Titan)", universe: "Attack on Titan", tier: "T14 - City Level" },
  { id: 203, name: "Ymir Fritz (Original Titan)", universe: "Attack on Titan", tier: "T2 - Beyond Multiversal" },
  { id: 204, name: "Rod Reiss", universe: "Attack on Titan", tier: "T17 - Wall Level" },
  { id: 205, name: "Hange Zoë", universe: "Attack on Titan", tier: "T16 - Building Level" },
  { id: 206, name: "Sasha Blouse", universe: "Attack on Titan", tier: "T19 - Peak Human" },
  { id: 207, name: "Jean Kirstein", universe: "Attack on Titan", tier: "T19 - Peak Human" },
  { id: 208, name: "Connie Springer", universe: "Attack on Titan", tier: "T19 - Peak Human" },
  { id: 209, name: "Erwin Smith", universe: "Attack on Titan", tier: "T16 - Building Level" },
  { id: 210, name: "Floch Forster", universe: "Attack on Titan", tier: "T18 - Street Level" },
  { id: 211, name: "Gabi Braun", universe: "Attack on Titan", tier: "T18 - Street Level" },
  { id: 212, name: "Pieck Finger (Cart Titan)", universe: "Attack on Titan", tier: "T14 - City Level" },
  { id: 213, name: "Kenny Ackerman", universe: "Attack on Titan", tier: "T17 - Wall Level" },
  { id: 214, name: "Keith Shadis", universe: "Attack on Titan", tier: "T19 - Peak Human" },
  { id: 215, name: "Hitch Dreyse", universe: "Attack on Titan", tier: "T19 - Peak Human" },
  { id: 216, name: "Marlo Freudenberg", universe: "Attack on Titan", tier: "T19 - Peak Human" },
];

export default function Home() {
  const [selectedTier, setSelectedTier] = useState(tiers[0]);

  const filtered = characters.filter(c => c.tier === selectedTier);

  return (
    <div style={{ padding: "1rem", fontFamily: "Arial, sans-serif" }}>
      <h1>All Tier List</h1>
      <div style={{ marginBottom: "1rem" }}>
        {tiers.map(tier => (
          <button
            key={tier}
            onClick={() => setSelectedTier(tier)}
            style={{
              marginRight: "0.5rem",
              padding: "0.5rem 1rem",
              background: selectedTier === tier ? "#222" : "#eee",
              color: selectedTier === tier ? "#fff" : "#000",
              border: "none",
              borderRadius: "4px",
              cursor: "pointer"
            }}
          >
            {tier}
          </button>
        ))}
      </div>

      <h2>{selectedTier} Tier Characters</h2>
      <ul>
        {filtered.map(c => (
          <li key={c.id}>
            <strong>{c.name}</strong> - {c.universe}
          </li>
        ))}
        {filtered.length === 0 && <li>No characters in this tier.</li>}
      </ul>
    </div>
  );
}
