import { useState } from "react";

const tiers = [
  "T1 - Omniversal",
  "T2 - Beyond Multiversal",
  "T3 - High Multiversal",
  "T4 - Multiversal+",
  "T5 - Multiversal",
  "T6 - Universal+",
  "T7 - Universal",
  "T8 - Large Planetary to Galaxy Level",
  "T9 - Star System Level",
  "T10 - Planetary",
  "T11 - Moon Level",
  "T12 - Continent Level",
  "T13 - Country Level",
  "T14 - City Level",
  "T15 - Mountain Level",
  "T16 - Building Level",
  "T17 - Wall Level",
  "T18 - Street Level",
  "T19 - Peak Human",
  "T20 - Regular Human" 
];


const characters = [
  { id: 1, name: "Rimuru Tempest", universe: "Slime Datta Ken", tier: "T5 - Multiversal" },
  { id: 2, name: "Diablo", universe: "Slime Datta Ken", tier: "T6 - Universal+" },
  { id: 3, name: "Shion", universe: "Slime Datta Ken", tier: "T8 - Large Planetary to Galaxy Level" },
  { id: 4, name: "Benimaru", universe: "Slime Datta Ken", tier: "T9 - Star System Level" },
  { id: 5, name: "Shuna", universe: "Slime Datta Ken", tier: "T14 - City Level" },
  { id: 6, name: "Souei", universe: "Slime Datta Ken", tier: "T8 - Large Planetary to Galaxy Level" },
  { id: 7, name: "Hakurou", universe: "Slime Datta Ken", tier: "T15 - Mountain Level" },
  { id: 8, name: "Ranga", universe: "Slime Datta Ken", tier: "T12 - Continent Level" },
  { id: 9, name: "Veldora Tempest", universe: "Slime Datta Ken", tier: "T4 - Multiversal+" },
  { id: 10, name: "Milim Nava", universe: "Slime Datta Ken", tier: "T3 - High Multiversal" },
  { id: 11, name: "Frey", universe: "Slime Datta Ken", tier: "T13 - Country Level" },
  { id: 12, name: "Gabil", universe: "Slime Datta Ken", tier: "T17 - Wall Level" },
  { id: 13, name: "Iroha", universe: "Slime Datta Ken", tier: "T15 - Mountain Level" },
  { id: 14, name: "Rigurdo", universe: "Slime Datta Ken", tier: "T18 - Street Level" },
  { id: 15, name: "Gobta", universe: "Slime Datta Ken", tier: "T20 - Regular Human" },
  { id: 16, name: "Ramiris", universe: "Slime Datta Ken", tier: "T7 - Universal" },
  { id: 17, name: "Geld", universe: "Slime Datta Ken", tier: "T6 - Universal+" },
  { id: 18, name: "Carrion", universe: "Slime Datta Ken", tier: "T11 - Moon Level" },
  { id: 19, name: "Clayman", universe: "Slime Datta Ken", tier: "T5 - Multiversal" },
  { id: 20, name: "Treyni", universe: "Slime Datta Ken", tier: "T14 - City Level" },
  { id: 21, name: "Hinata Sakaguchi", universe: "Slime Datta Ken", tier: "T9 - Star System Level" },
  { id: 22, name: "Kurobe", universe: "Slime Datta Ken", tier: "T16 - Building Level" },
  { id: 23, name: "Luminous Valentine", universe: "Slime Datta Ken", tier: "T13 - Country Level" },
  { id: 24, name: "Towa", universe: "Slime Datta Ken", tier: "T6 - Universal+" },
  { id: 25, name: "Kaguya Ōtsutsuki", universe: "Naruto", tier: "T2 - Beyond Multiversal" },
  { id: 26, name: "Hagoromo Ōtsutsuki (Sage of Six Paths)", universe: "Naruto", tier: "T3 - High Multiversal" },
  { id: 27, name: "Hamura Ōtsutsuki", universe: "Naruto", tier: "T4 - Multiversal+" },
  { id: 28, name: "Naruto Uzumaki (Sage Mode + Kurama)", universe: "Naruto", tier: "T5 - Multiversal" },
  { id: 29, name: "Sasuke Uchiha (Rinnegan + Eternal Mangekyo)", universe: "Naruto", tier: "T5 - Multiversal" },
  { id: 30, name: "Madara Uchiha (Ten Tails Jinchuriki)", universe: "Naruto", tier: "T5 - Multiversal" },
  { id: 31, name: "Hashirama Senju", universe: "Naruto", tier: "T7 - Universal" },
  { id: 32, name: "Obito Uchiha (Ten Tails Jinchuriki)", universe: "Naruto", tier: "T5 - Multiversal" },
  { id: 33, name: "Kakashi Hatake (Double Mangekyo Sharingan)", universe: "Naruto", tier: "T9 - Star System Level" },
  { id: 34, name: "Might Guy (Eighth Gate)", universe: "Naruto", tier: "T8 - Large Planetary to Galaxy Level" },
  { id: 35, name: "Minato Namikaze (Fourth Hokage)", universe: "Naruto", tier: "T10 - Planetary" },
  { id: 36, name: "Itachi Uchiha", universe: "Naruto", tier: "T11 - Moon Level" },
  { id: 37, name: "Tsunade Senju", universe: "Naruto", tier: "T14 - City Level" },
  { id: 38, name: "Gaara (Kazekage)", universe: "Naruto", tier: "T13 - Country Level" },
  { id: 39, name: "Shikamaru Nara", universe: "Naruto", tier: "T16 - Building Level" },
  { id: 40, name: "Neji Hyuga", universe: "Naruto", tier: "T15 - Mountain Level" },
  { id: 41, name: "Rock Lee (Without Eight Gates)", universe: "Naruto", tier: "T19 - Peak Human" },
  { id: 42, name: "Hinata Hyuga", universe: "Naruto", tier: "T18 - Street Level" },
  { id: 43, name: "Killer Bee", universe: "Naruto", tier: "T12 - Continent Level" },
  { id: 44, name: "Jiraiya", universe: "Naruto", tier: "T11 - Moon Level" },
  { id: 45, name: "Orochimaru", universe: "Naruto", tier: "T12 - Continent Level" },
  { id: 46, name: "Sai", universe: "Naruto", tier: "T16 - Building Level" },
  { id: 47, name: "Kurenai Yuhi", universe: "Naruto", tier: "T18 - Street Level" },
  { id: 48, name: "Asuma Sarutobi", universe: "Naruto", tier: "T18 - Street Level" },
  { id: 49, name: "Shino Aburame", universe: "Naruto", tier: "T18 - Street Level" },
  { id: 50, name: "Konohamaru Sarutobi", universe: "Naruto", tier: "T19 - Peak Human" },
  { id: 51, name: "Tenten", universe: "Naruto", tier: "T19 - Peak Human" },
  { id: 52, name: "Kiba Inuzuka", universe: "Naruto", tier: "T18 - Street Level" },
  { id: 53, name: "Shisui Uchiha", universe: "Naruto", tier: "T10 - Planetary" },
  { id: 54, name: "Obito Uchiha (Masked)", universe: "Naruto", tier: "T5 - Multiversal" },
  { id: 55, name: "Nagato (Pain)", universe: "Naruto", tier: "T7 - Universal" },
  { id: 56, name: "Killer Bee (Jinchuriki)", universe: "Naruto", tier: "T11 - Moon Level" },
  { id: 57, name: "Hiruzen Sarutobi (Third Hokage)", universe: "Naruto", tier: "T12 - Continent Level" },
  { id: 58, name: "Danzo Shimura", universe: "Naruto", tier: "T13 - Country Level" },
  { id: 59, name: "Kakuzu", universe: "Naruto", tier: "T13 - Country Level" },
  { id: 60, name: "Zabuza Momochi", universe: "Naruto", tier: "T17 - Wall Level" },
  { id: 61, name: "Haku", universe: "Naruto", tier: "T18 - Street Level" },
  { id: 62, name: "Kimimaro", universe: "Naruto", tier: "T14 - City Level" },
  { id: 63, name: "Yamato", universe: "Naruto", tier: "T14 - City Level" },
  { id: 64, name: "Sai (Anbu)", universe: "Naruto", tier: "T15 - Mountain Level" },
  { id: 65, name: "Kurenai Yuhi (Anbu)", universe: "Naruto", tier: "T16 - Building Level" },
  { id: 66, name: "Ino Yamanaka", universe: "Naruto", tier: "T18 - Street Level" },
  { id: 67, name: "Choji Akimichi", universe: "Naruto", tier: "T17 - Wall Level" },
  { id: 68, name: "Shikadai Nara", universe: "Naruto", tier: "T18 - Street Level" },
  { id: 69, name: "Boruto Uzumaki", universe: "Naruto", tier: "T17 - Wall Level" },
  { id: 70, name: "Sarada Uchiha", universe: "Naruto", tier: "T18 - Street Level" },
  { id: 71, name: "Gol D. Roger", universe: "One Piece", tier: "T7 - Universal" },
  { id: 72, name: "Whitebeard (Edward Newgate)", universe: "One Piece", tier: "T7 - Universal" },
  { id: 73, name: "Kaido", universe: "One Piece", tier: "T7 - Universal" },
  { id: 74, name: "Big Mom (Charlotte Linlin)", universe: "One Piece", tier: "T7 - Universal" },
  { id: 75, name: "Monkey D. Luffy (Gear 5)", universe: "One Piece", tier: "T9 - Star System Level" },
  { id: 76, name: "Shanks", universe: "One Piece", tier: "T8 - Large Planetary to Galaxy Level" },
  { id: 77, name: "Blackbeard (Marshall D. Teach)", universe: "One Piece", tier: "T7 - Universal" },
  { id: 78, name: "Admiral Akainu (Sakazuki)", universe: "One Piece", tier: "T8 - Large Planetary to Galaxy Level" },
  { id: 79, name: "Admiral Aokiji (Kuzan)", universe: "One Piece", tier: "T8 - Large Planetary to Galaxy Level" },
  { id: 80, name: "Admiral Kizaru (Borsalino)", universe: "One Piece", tier: "T8 - Large Planetary to Galaxy Level" },
  { id: 81, name: "Admiral Fujitora (Issho)", universe: "One Piece", tier: "T8 - Large Planetary to Galaxy Level" },
  { id: 82, name: "Dracule Mihawk", universe: "One Piece", tier: "T10 - Planetary" },
  { id: 83, name: "Trafalgar D. Water Law", universe: "One Piece", tier: "T11 - Moon Level" },
  { id: 84, name: "Eustass Kid", universe: "One Piece", tier: "T11 - Moon Level" },
  { id: 85, name: "Portgas D. Ace", universe: "One Piece", tier: "T12 - Continent Level" },
  { id: 86, name: "Sabo", universe: "One Piece", tier: "T12 - Continent Level" },
  { id: 87, name: "Roronoa Zoro", universe: "One Piece", tier: "T11 - Moon Level" },
  { id: 88, name: "Jinbe", universe: "One Piece", tier: "T13 - Country Level" },
  { id: 89, name: "Franky", universe: "One Piece", tier: "T15 - Mountain Level" },
  { id: 90, name: "Brook", universe: "One Piece", tier: "T17 - Wall Level" },
  { id: 91, name: "Nico Robin", universe: "One Piece", tier: "T16 - Building Level" },
  { id: 92, name: "Usopp", universe: "One Piece", tier: "T18 - Street Level" },
  { id: 93, name: "Sanji", universe: "One Piece", tier: "T14 - City Level" },
  { id: 94, name: "Chopper", universe: "One Piece", tier: "T18 - Street Level" },
  { id: 95, name: "Nami", universe: "One Piece", tier: "T18 - Street Level" },
  { id: 96, name: "Vinsmoke Judge", universe: "One Piece", tier: "T13 - Country Level" },
  { id: 97, name: "Vinsmoke Reiju", universe: "One Piece", tier: "T15 - Mountain Level" },
  { id: 98, name: "Charlotte Katakuri", universe: "One Piece", tier: "T11 - Moon Level" },
  { id: 99, name: "Charlotte Smoothie", universe: "One Piece", tier: "T13 - Country Level" },
  { id: 100, name: "Caesar Clown", universe: "One Piece", tier: "T14 - City Level" },
  { id: 101, name: "Donquixote Doflamingo", universe: "One Piece", tier: "T11 - Moon Level" },
  { id: 102, name: "Bartholomew Kuma", universe: "One Piece", tier: "T10 - Planetary" },
  { id: 103, name: "Kizaru (Borsalino)", universe: "One Piece", tier: "T8 - Large Planetary to Galaxy Level" },
  { id: 104, name: "Coby", universe: "One Piece", tier: "T15 - Mountain Level" },
  { id: 105, name: "Magellan", universe: "One Piece", tier: "T14 - City Level" },
  { id: 106, name: "Sentomaru", universe: "One Piece", tier: "T16 - Building Level" },
  { id: 107, name: "Killer", universe: "One Piece", tier: "T17 - Wall Level" },
  { id: 108, name: "Bon Clay (Mr. 2)", universe: "One Piece", tier: "T18 - Street Level" },
  { id: 109, name: "Franky (Battle Franky)", universe: "One Piece", tier: "T15 - Mountain Level" },
  { id: 110, name: "Brook (Soul King)", universe: "One Piece", tier: "T17 - Wall Level" },
  { id: 111, name: "Jozu", universe: "One Piece", tier: "T12 - Continent Level" },
  { id: 112, name: "Vista", universe: "One Piece", tier: "T13 - Country Level" },
  { id: 113, name: "Fujitora (Issho)", universe: "One Piece", tier: "T8 - Large Planetary to Galaxy Level" },
  { id: 114, name: "Kuma (Pacifista)", universe: "One Piece", tier: "T14 - City Level" },
  { id: 115, name: "Jewelry Bonney", universe: "One Piece", tier: "T17 - Wall Level" },
  { id: 116, name: "Meruem", universe: "Hunter x Hunter", tier: "T6 - Universal+" },
  { id: 117, name: "Netero", universe: "Hunter x Hunter", tier: "T8 - Large Planetary to Galaxy Level" },
  { id: 118, name: "Ging Freecss", universe: "Hunter x Hunter", tier: "T7 - Universal" },
  { id: 119, name: "Killua Zoldyck", universe: "Hunter x Hunter", tier: "T14 - City Level" },
  { id: 120, name: "Gon Freecss (Adult)", universe: "Hunter x Hunter", tier: "T7 - Universal" },
  { id: 121, name: "Hisoka Morow", universe: "Hunter x Hunter", tier: "T12 - Continent Level" },
  { id: 122, name: "Chrollo Lucilfer", universe: "Hunter x Hunter", tier: "T12 - Continent Level" },
  { id: 123, name: "Feitan Portor", universe: "Hunter x Hunter", tier: "T14 - City Level" },
  { id: 124, name: "Shalnark", universe: "Hunter x Hunter", tier: "T15 - Mountain Level" },
  { id: 125, name: "Pakunoda", universe: "Hunter x Hunter", tier: "T16 - Building Level" },
  { id: 126, name: "Illumi Zoldyck", universe: "Hunter x Hunter", tier: "T13 - Country Level" },
  { id: 127, name: "Leorio Paradinight", universe: "Hunter x Hunter", tier: "T18 - Street Level" },
  { id: 128, name: "Kurapika", universe: "Hunter x Hunter", tier: "T13 - Country Level" },
  { id: 129, name: "Biscuit Krueger", universe: "Hunter x Hunter", tier: "T15 - Mountain Level" },
  { id: 130, name: "Zeno Zoldyck", universe: "Hunter x Hunter", tier: "T9 - Star System Level" },
  { id: 131, name: "Silva Zoldyck", universe: "Hunter x Hunter", tier: "T9 - Star System Level" },
  { id: 132, name: "Menthuthuyoupi", universe: "Hunter x Hunter", tier: "T11 - Moon Level" },
  { id: 133, name: "Shaiapouf", universe: "Hunter x Hunter", tier: "T11 - Moon Level" },
  { id: 134, name: "Genthru", universe: "Hunter x Hunter", tier: "T16 - Building Level" },
  { id: 135, name: "Phinks", universe: "Hunter x Hunter", tier: "T15 - Mountain Level" },
  { id: 136, name: "Uvogin", universe: "Hunter x Hunter", tier: "T14 - City Level" },
  { id: 137, name: "Pakunoda", universe: "Hunter x Hunter", tier: "T16 - Building Level" },
  { id: 138, name: "Knuckle Bine", universe: "Hunter x Hunter", tier: "T15 - Mountain Level" },
  { id: 139, name: "Shoot McMahon", universe: "Hunter x Hunter", tier: "T15 - Mountain Level" },
  { id: 140, name: "Morel Mackernasey", universe: "Hunter x Hunter", tier: "T14 - City Level" },
  { id: 141, name: "Machi Komacine", universe: "Hunter x Hunter", tier: "T16 - Building Level" },
  { id: 142, name: "Franklin Bordeau", universe: "Hunter x Hunter", tier: "T15 - Mountain Level" },
  { id: 143, name: "Kortopi", universe: "Hunter x Hunter", tier: "T17 - Wall Level" },
  { id: 144, name: "Shizuku Murasaki", universe: "Hunter x Hunter", tier: "T17 - Wall Level" },
  { id: 145, name: "Neferpitou", universe: "Hunter x Hunter", tier: "T10 - Planetary" },
  { id: 146, name: "Knov", universe: "Hunter x Hunter", tier: "T14 - City Level" },
  { id: 147, name: "Palm Siberia", universe: "Hunter x Hunter", tier: "T13 - Country Level" },
  { id: 148, name: "Ikalgo", universe: "Hunter x Hunter", tier: "T16 - Building Level" },
  { id: 149, name: "Gon Freecss (Child)", universe: "Hunter x Hunter", tier: "T17 - Wall Level" },
  { id: 150, name: "Killua Zoldyck (Child)", universe: "Hunter x Hunter", tier: "T17 - Wall Level" },
  { id: 151, name: "Komugi", universe: "Hunter x Hunter", tier: "T20 - Regular Human" },
  { id: 152, name: "Zushi", universe: "Hunter x Hunter", tier: "T18 - Street Level" },
  { id: 153, name: "Colt", universe: "Hunter x Hunter", tier: "T15 - Mountain Level" },
  { id: 154, name: "Welfin", universe: "Hunter x Hunter", tier: "T16 - Building Level" },
  { id: 155, name: "Knov", universe: "Hunter x Hunter", tier: "T14 - City Level" },
  { id: 156, name: "Kite", universe: "Hunter x Hunter", tier: "T13 - Country Level" },
  { id: 157, name: "Zagred", universe: "Hunter x Hunter", tier: "T5 - Multiversal" },
  { id: 158, name: "Beyond Netero", universe: "Hunter x Hunter", tier: "T6 - Universal+" },
  { id: 159, name: "Cheadle Yorkshire", universe: "Hunter x Hunter", tier: "T15 - Mountain Level" },
  { id: 160, name: "Meleoron", universe: "Hunter x Hunter", tier: "T16 - Building Level" },
  { id: 161, name: "Knuckle Bine", universe: "Hunter x Hunter", tier: "T15 - Mountain Level" },
  { id: 162, name: "Pariston Hill", universe: "Hunter x Hunter", tier: "T16 - Building Level" },
  { id: 163, name: "Yami Sukehiro", universe: "Black Clover", tier: "T8 - Large Planetary to Galaxy Level" },
  { id: 164, name: "Asta (Devil Form)", universe: "Black Clover", tier: "T7 - Universal" },
  { id: 165, name: "Noelle Silva", universe: "Black Clover", tier: "T13 - Country Level" },
  { id: 166, name: "Luck Voltia", universe: "Black Clover", tier: "T14 - City Level" },
  { id: 167, name: "Finral Roulacase", universe: "Black Clover", tier: "T16 - Building Level" },
  { id: 168, name: "Charmy Pappitson", universe: "Black Clover", tier: "T18 - Street Level" },
  { id: 169, name: "Gauche Adlai", universe: "Black Clover", tier: "T15 - Mountain Level" },
  { id: 170, name: "Mimosa Vermillion", universe: "Black Clover", tier: "T17 - Wall Level" },
  { id: 171, name: "Magna Swing", universe: "Black Clover", tier: "T16 - Building Level" },
  { id: 172, name: "Gordon Agrippa", universe: "Black Clover", tier: "T20 - Regular Human" },
  { id: 173, name: "Zora Ideale", universe: "Black Clover", tier: "T15 - Mountain Level" },
  { id: 174, name: "Vanessa Enoteca", universe: "Black Clover", tier: "T13 - Country Level" },
  { id: 175, name: "Yuno", universe: "Black Clover", tier: "T6 - Universal+" },
  { id: 176, name: "William Vangeance", universe: "Black Clover", tier: "T5 - Multiversal" },
  { id: 177, name: "Mereoleona Vermillion", universe: "Black Clover", tier: "T9 - Star System Level" },
  { id: 178, name: "Fuegoleon Vermillion", universe: "Black Clover", tier: "T10 - Planetary" },
  { id: 179, name: "Secre Swallowtail", universe: "Black Clover", tier: "T15 - Mountain Level" },
  { id: 180, name: "Nozel Silva", universe: "Black Clover", tier: "T11 - Moon Level" },
  { id: 181, name: "Rill Boismortier", universe: "Black Clover", tier: "T16 - Building Level" },
  { id: 182, name: "Licht", universe: "Black Clover", tier: "T4 - Multiversal+" },
  { id: 183, name: "Patolli", universe: "Black Clover", tier: "T4 - Multiversal+" },
  { id: 184, name: "Fana", universe: "Black Clover", tier: "T5 - Multiversal" },
  { id: 185, name: "Rades Spirito", universe: "Black Clover", tier: "T12 - Continent Level" },
  { id: 186, name: "Langris Vaude", universe: "Black Clover", tier: "T7 - Universal" },
  { id: 187, name: "Zagred", universe: "Black Clover", tier: "T3 - High Multiversal" },
  { id: 188, name: "Lolopechka", universe: "Black Clover", tier: "T13 - Country Level" },
  { id: 189, name: "Dorothy Unsworth", universe: "Black Clover", tier: "T10 - Planetary" },
  { id: 190, name: "Ruben", universe: "Black Clover", tier: "T19 - Peak Human" },
  { id: 191, name: "Mars", universe: "Black Clover", tier: "T14 - City Level" },
  { id: 192, name: "Kaiser Granvorka", universe: "Black Clover", tier: "T13 - Country Level" },
  { id: 193, name: "Eren Yeager (Founding Titan)", universe: "Attack on Titan", tier: "T4 - Multiversal+" },
  { id: 194, name: "Armin Arlert (Colossal Titan)", universe: "Attack on Titan", tier: "T10 - Planetary" },
  { id: 195, name: "Reiner Braun (Armored Titan)", universe: "Attack on Titan", tier: "T12 - Continent Level" },
  { id: 196, name: "Annie Leonhart (Female Titan)", universe: "Attack on Titan", tier: "T12 - Continent Level" },
  { id: 197, name: "Zeke Yeager (Beast Titan)", universe: "Attack on Titan", tier: "T11 - Moon Level" },
  { id: 198, name: "Levi Ackerman", universe: "Attack on Titan", tier: "T16 - Building Level" },
  { id: 199, name: "Mikasa Ackerman", universe: "Attack on Titan", tier: "T15 - Mountain Level" },
  { id: 200, name: "Historia Reiss", universe: "Attack on Titan", tier: "T18 - Street Level" },
  { id: 201, name: "Porco Galliard (Jaw Titan)", universe: "Attack on Titan", tier: "T14 - City Level" },
  { id: 202, name: "Pieck Finger (Cart Titan)", universe: "Attack on Titan", tier: "T14 - City Level" },
  { id: 203, name: "Ymir Fritz (Original Titan)", universe: "Attack on Titan", tier: "T2 - Beyond Multiversal" },
  { id: 204, name: "Rod Reiss", universe: "Attack on Titan", tier: "T17 - Wall Level" },
  { id: 205, name: "Hange Zoë", universe: "Attack on Titan", tier: "T16 - Building Level" },
  { id: 206, name: "Sasha Blouse", universe: "Attack on Titan", tier: "T19 - Peak Human" },
  { id: 207, name: "Jean Kirstein", universe: "Attack on Titan", tier: "T19 - Peak Human" },
  { id: 208, name: "Connie Springer", universe: "Attack on Titan", tier: "T19 - Peak Human" },
  { id: 209, name: "Erwin Smith", universe: "Attack on Titan", tier: "T16 - Building Level" },
  { id: 210, name: "Floch Forster", universe: "Attack on Titan", tier: "T18 - Street Level" },
  { id: 211, name: "Gabi Braun", universe: "Attack on Titan", tier: "T18 - Street Level" },
  { id: 212, name: "Pieck Finger (Cart Titan)", universe: "Attack on Titan", tier: "T14 - City Level" },
  { id: 213, name: "Kenny Ackerman", universe: "Attack on Titan", tier: "T17 - Wall Level" },
  { id: 214, name: "Keith Shadis", universe: "Attack on Titan", tier: "T19 - Peak Human" },
  { id: 215, name: "Hitch Dreyse", universe: "Attack on Titan", tier: "T19 - Peak Human" },
  { id: 216, name: "Marlo Freudenberg", universe: "Attack on Titan", tier: "T19 - Peak Human" },
  { id: 217, name: "Tanjiro Kamado", universe: "Demon Slayer", tier: "T13 - Country Level" },
  { id: 218, name: "Nezuko Kamado", universe: "Demon Slayer", tier: "T12 - Continent Level" },
  { id: 219, name: "Zenitsu Agatsuma", universe: "Demon Slayer", tier: "T14 - City Level" },
  { id: 220, name: "Inosuke Hashibira", universe: "Demon Slayer", tier: "T14 - City Level" },
  { id: 221, name: "Giyu Tomioka", universe: "Demon Slayer", tier: "T11 - Moon Level" },
  { id: 222, name: "Shinobu Kocho", universe: "Demon Slayer", tier: "T15 - Mountain Level" },
  { id: 223, name: "Kyojuro Rengoku", universe: "Demon Slayer", tier: "T10 - Planetary" },
  { id: 224, name: "Tengen Uzui", universe: "Demon Slayer", tier: "T12 - Continent Level" },
  { id: 225, name: "Mitsuri Kanroji", universe: "Demon Slayer", tier: "T15 - Mountain Level" },
  { id: 226, name: "Muichiro Tokito", universe: "Demon Slayer", tier: "T13 - Country Level" },
  { id: 227, name: "Gyomei Himejima", universe: "Demon Slayer", tier: "T9 - Star System Level" },
  { id: 228, name: "Sanemi Shinazugawa", universe: "Demon Slayer", tier: "T14 - City Level" },
  { id: 229, name: "Obanai Iguro", universe: "Demon Slayer", tier: "T14 - City Level" },
  { id: 230, name: "Kagaya Ubuyashiki", universe: "Demon Slayer", tier: "T16 - Building Level" },
  { id: 231, name: "Akaza", universe: "Demon Slayer", tier: "T8 - Large Planetary to Galaxy Level" },
  { id: 232, name: "Doma", universe: "Demon Slayer", tier: "T7 - Universal" },
  { id: 233, name: "Kokushibo", universe: "Demon Slayer", tier: "T6 - Universal+" },
  { id: 234, name: "Enmu", universe: "Demon Slayer", tier: "T18 - Street Level" },
  { id: 235, name: "Gyutaro", universe: "Demon Slayer", tier: "T14 - City Level" },
  { id: 236, name: "Rui", universe: "Demon Slayer", tier: "T15 - Mountain Level" },
  { id: 237, name: "Nakime", universe: "Demon Slayer", tier: "T16 - Building Level" },
  { id: 238, name: "Hantengu", universe: "Demon Slayer", tier: "T12 - Continent Level" },
  { id: 239, name: "Kaigaku", universe: "Demon Slayer", tier: "T13 - Country Level" },
  { id: 240, name: "Tamayo", universe: "Demon Slayer", tier: "T19 - Peak Human" },
  { id: 241, name: "Yushiro", universe: "Demon Slayer", tier: "T19 - Peak Human" },
  { id: 242, name: "Sabito", universe: "Demon Slayer", tier: "T19 - Peak Human" },
  { id: 243, name: "Makomo", universe: "Demon Slayer", tier: "T19 - Peak Human" },
  { id: 244, name: "Kanao Tsuyuri", universe: "Demon Slayer", tier: "T14 - City Level" },
  { id: 245, name: "Sumiyoshi", universe: "Demon Slayer", tier: "T20 - Regular Human" },
  { id: 246, name: "Hinaki Ubuyashiki", universe: "Demon Slayer", tier: "T20 - Regular Human" },
  { id: 247, name: "Shinjuro Rengoku", universe: "Demon Slayer", tier: "T16 - Building Level" },
  { id: 248, name: "Kiriya Ubuyashiki", universe: "Demon Slayer", tier: "T19 - Peak Human" },
  { id: 249, name: "Yoriichi Tsugikuni", universe: "Demon Slayer", tier: "T3 - High Multiversal" },
  { id: 250, name: "Tanjuro Kamado", universe: "Demon Slayer", tier: "T15 - Mountain Level" },
  { id: 251, name: "Hinokami Kagura (Dance of the Fire God)", universe: "Demon Slayer", tier: "T14 - City Level" },
  { id: 252, name: "Daki", universe: "Demon Slayer", tier: "T13 - Country Level" },
  { id: 253, name: "Michikatsu Tsugikuni", universe: "Demon Slayer", tier: "T15 - Mountain Level" },
  { id: 254, name: "Kanae Kocho", universe: "Demon Slayer", tier: "T16 - Building Level" },
  { id: 255, name: "Izuku Midoriya (Deku)", universe: "My Hero Academia", tier: "T11 - Moon Level" },
  { id: 256, name: "Katsuki Bakugo", universe: "My Hero Academia", tier: "T12 - Continent Level" },
  { id: 257, name: "Shoto Todoroki", universe: "My Hero Academia", tier: "T12 - Continent Level" },
  { id: 258, name: "All Might (Prime)", universe: "My Hero Academia", tier: "T7 - Universal" },
  { id: 259, name: "All For One", universe: "My Hero Academia", tier: "T4 - Multiversal+" },
  { id: 260, name: "Tomura Shigaraki", universe: "My Hero Academia", tier: "T5 - Multiversal" },
  { id: 261, name: "Endeavor (Enji Todoroki)", universe: "My Hero Academia", tier: "T9 - Star System Level" },
  { id: 262, name: "Mirio Togata (Lemillion)", universe: "My Hero Academia", tier: "T10 - Planetary" },
  { id: 263, name: "Hawks (Keigo Takami)", universe: "My Hero Academia", tier: "T11 - Moon Level" },
  { id: 264, name: "Eraser Head (Shota Aizawa)", universe: "My Hero Academia", tier: "T14 - City Level" },
  { id: 265, name: "Momo Yaoyorozu", universe: "My Hero Academia", tier: "T15 - Mountain Level" },
  { id: 266, name: "Tsuyu Asui", universe: "My Hero Academia", tier: "T16 - Building Level" },
  { id: 267, name: "Minoru Mineta", universe: "My Hero Academia", tier: "T19 - Peak Human" },
  { id: 268, name: "Denki Kaminari", universe: "My Hero Academia", tier: "T17 - Wall Level" },
  { id: 269, name: "Ochaco Uraraka", universe: "My Hero Academia", tier: "T16 - Building Level" },
  { id: 270, name: "Tenya Iida", universe: "My Hero Academia", tier: "T15 - Mountain Level" },
  { id: 271, name: "Fumikage Tokoyami", universe: "My Hero Academia", tier: "T14 - City Level" },
  { id: 272, name: "Kyoka Jiro", universe: "My Hero Academia", tier: "T17 - Wall Level" },
  { id: 273, name: "Mina Ashido", universe: "My Hero Academia", tier: "T18 - Street Level" },
  { id: 274, name: "Yuga Aoyama", universe: "My Hero Academia", tier: "T18 - Street Level" },
  { id: 275, name: "Rikido Sato", universe: "My Hero Academia", tier: "T16 - Building Level" },
  { id: 276, name: "Mezo Shoji", universe: "My Hero Academia", tier: "T16 - Building Level" },
  { id: 277, name: "Hanta Sero", universe: "My Hero Academia", tier: "T18 - Street Level" },
  { id: 278, name: "Koji Koda", universe: "My Hero Academia", tier: "T19 - Peak Human" },
  { id: 279, name: "Mashirao Ojiro", universe: "My Hero Academia", tier: "T19 - Peak Human" },
  { id: 280, name: "Minoru Mineta", universe: "My Hero Academia", tier: "T19 - Peak Human" },
  { id: 281, name: "Nejire Hado", universe: "My Hero Academia", tier: "T13 - Country Level" },
  { id: 282, name: "Tamaki Amajiki", universe: "My Hero Academia", tier: "T13 - Country Level" },
  { id: 283, name: "Hitoshi Shinso", universe: "My Hero Academia", tier: "T16 - Building Level" },
  { id: 284, name: "Eri", universe: "My Hero Academia", tier: "T8 - Large Planetary to Galaxy Level" },
  { id: 285, name: "Katsuma Shimano", universe: "My Hero Academia", tier: "T20 - Regular Human" },
  { id: 286, name: "Inko Midoriya", universe: "My Hero Academia", tier: "T20 - Regular Human" },
  { id: 287, name: "Gigantomachia", universe: "My Hero Academia", tier: "T10 - Planetary" },
  { id: 288, name: "Dabi", universe: "My Hero Academia", tier: "T11 - Moon Level" },
  { id: 289, name: "Himiko Toga", universe: "My Hero Academia", tier: "T17 - Wall Level" },
  { id: 290, name: "Kurogiri", universe: "My Hero Academia", tier: "T15 - Mountain Level" },
  { id: 291, name: "Goku (Ultra Instinct)", universe: "Dragon Ball", tier: "T3 - High Multiversal" },
  { id: 292, name: "Vegeta (Ultra Ego)", universe: "Dragon Ball", tier: "T4 - Multiversal+" },
  { id: 293, name: "Jiren", universe: "Dragon Ball", tier: "T4 - Multiversal+" },
  { id: 294, name: "Broly (Legendary Super Saiyan)", universe: "Dragon Ball", tier: "T5 - Multiversal" },
  { id: 295, name: "Beerus", universe: "Dragon Ball", tier: "T2 - Beyond Multiversal" },
  { id: 296, name: "Whis", universe: "Dragon Ball", tier: "T1 - Godlike Multiversal" },
  { id: 297, name: "Frieza (Golden Form)", universe: "Dragon Ball", tier: "T6 - Universal+" },
  { id: 298, name: "Cell (Perfect Form)", universe: "Dragon Ball", tier: "T10 - Planetary" },
  { id: 299, name: "Majin Buu (Kid Buu)", universe: "Dragon Ball", tier: "T5 - Multiversal" },
  { id: 300, name: "Gohan (Potential Unleashed)", universe: "Dragon Ball", tier: "T7 - Universal" },
  { id: 301, name: "Trunks (Future)", universe: "Dragon Ball", tier: "T8 - Large Planetary to Galaxy Level" },
  { id: 302, name: "Piccolo", universe: "Dragon Ball", tier: "T9 - Star System Level" },
  { id: 303, name: "Android 17", universe: "Dragon Ball", tier: "T10 - Planetary" },
  { id: 304, name: "Android 18", universe: "Dragon Ball", tier: "T16 - Building Level" },
  { id: 305, name: "Krillin", universe: "Dragon Ball", tier: "T18 - Street Level" },
  { id: 306, name: "Tien Shinhan", universe: "Dragon Ball", tier: "T17 - Wall Level" },
  { id: 307, name: "Yamcha", universe: "Dragon Ball", tier: "T19 - Peak Human" },
  { id: 308, name: "Master Roshi", universe: "Dragon Ball", tier: "T20 - Regular Human" },
  { id: 309, name: "Whis (Alternative Form)", universe: "Dragon Ball", tier: "T1 - Godlike Multiversal" },
  { id: 310, name: "Zamasu (Fused)", universe: "Dragon Ball", tier: "T4 - Multiversal+" },
  { id: 311, name: "Goku Black", universe: "Dragon Ball", tier: "T4 - Multiversal+" },
  { id: 312, name: "Hit", universe: "Dragon Ball", tier: "T7 - Universal" },
  { id: 313, name: "Cabba", universe: "Dragon Ball", tier: "T15 - Mountain Level" },
  { id: 314, name: "Caulifla", universe: "Dragon Ball", tier: "T14 - City Level" },
  { id: 315, name: "Kale", universe: "Dragon Ball", tier: "T13 - Country Level" },
  { id: 316, name: "Toppo", universe: "Dragon Ball", tier: "T9 - Star System Level" },
  { id: 317, name: "Dyspo", universe: "Dragon Ball", tier: "T10 - Planetary" },
  { id: 318, name: "Kefla", universe: "Dragon Ball", tier: "T7 - Universal" },
  { id: 319, name: "Gotenks", universe: "Dragon Ball", tier: "T10 - Planetary" },
  { id: 320, name: "Vegito (Super Saiyan Blue)", universe: "Dragon Ball", tier: "T2 - Beyond Multiversal" },
  { id: 321, name: "Gogeta (Super Saiyan Blue)", universe: "Dragon Ball", tier: "T2 - Beyond Multiversal" },
  { id: 322, name: "Ichigo Kurosaki (Final Getsuga Tensho)", universe: "Bleach", tier: "T4 - Multiversal+" },
  { id: 323, name: "Sosuke Aizen", universe: "Bleach", tier: "T5 - Multiversal" },
  { id: 324, name: "Yhwach", universe: "Bleach", tier: "T2 - Beyond Multiversal" },
  { id: 325, name: "Genryūsai Shigekuni Yamamoto", universe: "Bleach", tier: "T3 - High Multiversal" },
  { id: 326, name: "Kenpachi Zaraki", universe: "Bleach", tier: "T8 - Large Planetary to Galaxy Level" },
  { id: 327, name: "Rukia Kuchiki", universe: "Bleach", tier: "T16 - Building Level" },
  { id: 328, name: "Byakuya Kuchiki", universe: "Bleach", tier: "T9 - Star System Level" },
  { id: 329, name: "Toshiro Hitsugaya", universe: "Bleach", tier: "T13 - Country Level" },
  { id: 330, name: "Uryu Ishida", universe: "Bleach", tier: "T14 - City Level" },
  { id: 331, name: "Shunsui Kyoraku", universe: "Bleach", tier: "T7 - Universal" },
  { id: 332, name: "Mayuri Kurotsuchi", universe: "Bleach", tier: "T12 - Continent Level" },
  { id: 333, name: "Ichigo Kurosaki (Bankai)", universe: "Bleach", tier: "T6 - Universal+" },
  { id: 334, name: "Yoruichi Shihouin", universe: "Bleach", tier: "T15 - Mountain Level" },
  { id: 335, name: "Kisuke Urahara", universe: "Bleach", tier: "T11 - Moon Level" },
  { id: 336, name: "Hollow Ichigo", universe: "Bleach", tier: "T4 - Multiversal+" },
  { id: 337, name: "Ulquiorra Cifer", universe: "Bleach", tier: "T9 - Star System Level" },
  { id: 338, name: "Grimmjow Jaegerjaquez", universe: "Bleach", tier: "T12 - Continent Level" },
  { id: 339, name: "Nnoitra Gilga", universe: "Bleach", tier: "T14 - City Level" },
  { id: 340, name: "Barragan Luisenbarn", universe: "Bleach", tier: "T6 - Universal+" },
  { id: 341, name: "Coyote Starrk", universe: "Bleach", tier: "T8 - Large Planetary to Galaxy Level" },
  { id: 342, name: "Shinji Hirako", universe: "Bleach", tier: "T15 - Mountain Level" },
  { id: 343, name: "Kyouraku Shunsui (Bankai)", universe: "Bleach", tier: "T5 - Multiversal" },
  { id: 344, name: "Urahara Kisuke (Bankai)", universe: "Bleach", tier: "T7 - Universal" },
  { id: 345, name: "Zaraki Kenpachi (Bankai)", universe: "Bleach", tier: "T7 - Universal" },
  { id: 346, name: "Ichigo Kurosaki (Hollow Mask)", universe: "Bleach", tier: "T6 - Universal+" },
  { id: 347, name: "Yhwach (Final Form)", universe: "Bleach", tier: "T1 - Godlike Multiversal" },
  { id: 348, name: "Natsu Dragneel (Dragon Force)", universe: "Fairy Tail", tier: "T9 - Star System Level" },
  { id: 349, name: "Zeref Dragneel", universe: "Fairy Tail", tier: "T2 - Beyond Multiversal" },
  { id: 350, name: "Acnologia", universe: "Fairy Tail", tier: "T1 - Godlike Multiversal" },
  { id: 351, name: "Erza Scarlet", universe: "Fairy Tail", tier: "T10 - Planetary" },
  { id: 352, name: "Gray Fullbuster", universe: "Fairy Tail", tier: "T14 - City Level" },
  { id: 353, name: "Lucy Heartfilia", universe: "Fairy Tail", tier: "T17 - Wall Level" },
  { id: 354, name: "Gajeel Redfox", universe: "Fairy Tail", tier: "T13 - Country Level" },
  { id: 355, name: "Wendy Marvell", universe: "Fairy Tail", tier: "T16 - Building Level" },
  { id: 356, name: "Laxus Dreyar", universe: "Fairy Tail", tier: "T8 - Large Planetary to Galaxy Level" },
  { id: 357, name: "Makarov Dreyar", universe: "Fairy Tail", tier: "T7 - Universal" },
  { id: 358, name: "Juvia Lockser", universe: "Fairy Tail", tier: "T15 - Mountain Level" },
  { id: 359, name: "Gildarts Clive", universe: "Fairy Tail", tier: "T6 - Universal+" },
  { id: 360, name: "Mirajane Strauss", universe: "Fairy Tail", tier: "T12 - Continent Level" },
  { id: 361, name: "Elfman Strauss", universe: "Fairy Tail", tier: "T18 - Street Level" },
  { id: 362, name: "Loke (Leo)", universe: "Fairy Tail", tier: "T5 - Multiversal" },
  { id: 363, name: "Panther Lily", universe: "Fairy Tail", tier: "T20 - Regular Human" },
  { id: 364, name: "Cana Alberona", universe: "Fairy Tail", tier: "T19 - Peak Human" },
  { id: 365, name: "Evergreen", universe: "Fairy Tail", tier: "T11 - Moon Level" },
  { id: 366, name: "Kagura Mikazuchi", universe: "Fairy Tail", tier: "T14 - City Level" },
  { id: 367, name: "Jose Porla", universe: "Fairy Tail", tier: "T13 - Country Level" },
  { id: 368, name: "Jellal Fernandes", universe: "Fairy Tail", tier: "T9 - Star System Level" },
  { id: 369, name: "Brandish μ", universe: "Fairy Tail", tier: "T8 - Large Planetary to Galaxy Level" },
  { id: 370, name: "Larcade Dragneel", universe: "Fairy Tail", tier: "T15 - Mountain Level" },
  { id: 371, name: "August", universe: "Fairy Tail", tier: "T3 - High Multiversal" },
  { id: 372, name: "Invel Yura", universe: "Fairy Tail", tier: "T7 - Universal" },
  { id: 373, name: "Dimaria Yesta", universe: "Fairy Tail", tier: "T6 - Universal+" },
  { id: 374, name: "Irene Belserion", universe: "Fairy Tail", tier: "T4 - Multiversal+" },
  { id: 375, name: "Zancrow", universe: "Fairy Tail", tier: "T12 - Continent Level" },
  { id: 376, name: "Rogue Cheney", universe: "Fairy Tail", tier: "T10 - Planetary" },
  { id: 377, name: "Sting Eucliffe", universe: "Fairy Tail", tier: "T10 - Planetary" },
  { id: 378, name: "Jason", universe: "Beginning After The End", tier: "T12 - Continent Level" },
  { id: 379, name: "Sylvie", universe: "Beginning After The End", tier: "T14 - City Level" },
  { id: 380, name: "Teresia", universe: "Beginning After The End", tier: "T15 - Mountain Level" },
  { id: 381, name: "Kris", universe: "Beginning After The End", tier: "T13 - Country Level" },
  { id: 382, name: "Galan", universe: "Beginning After The End", tier: "T11 - Moon Level" },
  { id: 383, name: "Arthur", universe: "Beginning After The End", tier: "T14 - City Level" },
  { id: 384, name: "Emilia", universe: "Beginning After The End", tier: "T16 - Building Level" },
  { id: 385, name: "Farrah", universe: "Beginning After The End", tier: "T18 - Street Level" },
  { id: 386, name: "Magnus", universe: "Beginning After The End", tier: "T10 - Planetary" },
  { id: 387, name: "Alexia", universe: "Beginning After The End", tier: "T12 - Continent Level" },
  
 { id: 388, name: "Ainz Ooal Gown", universe: "Overlord", tier: "T5 - Multiversal" },
  { id: 389, name: "Albedo", universe: "Overlord", tier: "T8 - Large Planetary to Galaxy Level" },
  { id: 390, name: "Shalltear Bloodfallen", universe: "Overlord", tier: "T9 - Star System Level" },
  { id: 391, name: "Demiurge", universe: "Overlord", tier: "T10 - Planetary" },
  { id: 392, name: "Cocytus", universe: "Overlord", tier: "T12 - Continent Level" },
  { id: 393, name: "Mare Bello Fiore", universe: "Overlord", tier: "T14 - City Level" },
  { id: 394, name: "Aura Bella Fiora", universe: "Overlord", tier: "T14 - City Level" },
  { id: 395, name: "Sebas Tian", universe: "Overlord", tier: "T15 - Mountain Level" },
  { id: 396, name: "Nigun Grid Luin", universe: "Overlord", tier: "T18 - Street Level" },
  { id: 397, name: "Pandora's Actor", universe: "Overlord", tier: "T11 - Moon Level" },
  { id: 398, name: "Victim", universe: "Overlord", tier: "T16 - Building Level" },
  { id: 399, name: "Evileye", universe: "Overlord", tier: "T19 - Peak Human" },
  { id: 400, name: "Lupusregina Beta", universe: "Overlord", tier: "T17 - Wall Level" },
  { id: 401, name: "Narberal Gamma", universe: "Overlord", tier: "T13 - Country Level" },
  { id: 402, name: "Solution Epsilon", universe: "Overlord", tier: "T20 - Regular Human" },
  { id: 403, name: "Brain Unglaus", universe: "Overlord", tier: "T19 - Peak Human" },
  { id: 404, name: "Kyouhukou", universe: "Overlord", tier: "T18 - Street Level" },
  { id: 405, name: "Gondolo", universe: "Overlord", tier: "T15 - Mountain Level" },
  { id: 406, name: "Clementine", universe: "Overlord", tier: "T16 - Building Level" },
  { id: 407, name: "Gazef Stronoff", universe: "Overlord", tier: "T14 - City Level" },
  { id: 408, name: "Zanac Valleon Igana Ryle Vaiself", universe: "Overlord", tier: "T8 - Large Planetary to Galaxy Level" },
  { id: 409, name: "King Shalltear Bloodfallen", universe: "Overlord", tier: "T9 - Star System Level" },
  { id: 410, name: "Entoma Vasilissa Zeta", universe: "Overlord", tier: "T15 - Mountain Level" },
  { id: 411, name: "Czernobog", universe: "Overlord", tier: "T10 - Planetary" },
  { id: 412, name: "Lakyus Alvein Dale Aindra", universe: "Overlord", tier: "T13 - Country Level" },
  { id: 413, name: "Naofumi Iwatani", universe: "The Rising of the Shield Hero", tier: "T12 - Continent Level" },
  { id: 414, name: "Raphtalia", universe: "The Rising of the Shield Hero", tier: "T14 - City Level" },
  { id: 415, name: "Filo", universe: "The Rising of the Shield Hero", tier: "T13 - Country Level" },
  { id: 416, name: "Motoyasu Kitamura", universe: "The Rising of the Shield Hero", tier: "T11 - Moon Level" },
  { id: 417, name: "Ren Amaki", universe: "The Rising of the Shield Hero", tier: "T11 - Moon Level" },
  { id: 418, name: "Itsuki Kawasumi", universe: "The Rising of the Shield Hero", tier: "T10 - Planetary" },
  { id: 419, name: "Melty Q Melromarc", universe: "The Rising of the Shield Hero", tier: "T15 - Mountain Level" },
  { id: 420, name: "Glass", universe: "The Rising of the Shield Hero", tier: "T16 - Building Level" },
  { id: 421, name: "Kizuna", universe: "The Rising of the Shield Hero", tier: "T14 - City Level" },
  { id: 422, name: "Aultcray Melromarc XXXII", universe: "The Rising of the Shield Hero", tier: "T9 - Star System Level" },
  { id: 423, name: "Rudeus Greyrat", universe: "Mushoku Tensei", tier: "T14 - City Level" },
  { id: 424, name: "Paul Greyrat", universe: "Mushoku Tensei", tier: "T15 - Mountain Level" },
  { id: 425, name: "Zenith Greyrat", universe: "Mushoku Tensei", tier: "T14 - City Level" },
  { id: 426, name: "Eris Boreas Greyrat", universe: "Mushoku Tensei", tier: "T15 - Mountain Level" },
  { id: 427, name: "Orsted", universe: "Mushoku Tensei", tier: "T6 - Universal+" },
  { id: 428, name: "Sylphiette", universe: "Mushoku Tensei", tier: "T16 - Building Level" },
  { id: 429, name: "Ghislaine Dedoldia", universe: "Mushoku Tensei", tier: "T15 - Mountain Level" },
  { id: 430, name: "Roxy Migurdia", universe: "Mushoku Tensei", tier: "T14 - City Level" },
  { id: 431, name: "Lilia", universe: "Mushoku Tensei", tier: "T17 - Wall Level" },
  { id: 432, name: "Rudeus Greyrat (Awakened)", universe: "Mushoku Tensei", tier: "T9 - Star System Level" },
  { id: 433, name: "Kirito (SAO)", universe: "Sword Art Online", tier: "T11 - Moon Level" },
  { id: 434, name: "Asuna", universe: "Sword Art Online", tier: "T12 - Continent Level" },
  { id: 435, name: "Eugeo", universe: "Sword Art Online", tier: "T13 - Country Level" },
  { id: 436, name: "Alice Zuberg", universe: "Sword Art Online", tier: "T10 - Planetary" },
  { id: 437, name: "Sinon", universe: "Sword Art Online", tier: "T14 - City Level" },
  { id: 438, name: "Subaru Natsuki", universe: "Re:Zero", tier: "T15 - Mountain Level" },
  { id: 439, name: "Emilia", universe: "Re:Zero", tier: "T9 - Star System Level" },
  { id: 440, name: "Rem", universe: "Re:Zero", tier: "T12 - Continent Level" },
  { id: 441, name: "Ram", universe: "Re:Zero", tier: "T14 - City Level" },
  { id: 442, name: "Beatrice", universe: "Re:Zero", tier: "T11 - Moon Level" },
  { id: 443, name: "Roswaal L Mathers", universe: "Re:Zero", tier: "T8 - Large Planetary to Galaxy Level" },
  { id: 444, name: "Felt", universe: "Re:Zero", tier: "T19 - Peak Human" },
  { id: 445, name: "Crusch Karsten", universe: "Re:Zero", tier: "T13 - Country Level" },
  { id: 446, name: "Petra Leyte", universe: "Re:Zero", tier: "T18 - Street Level" },
  { id: 447, name: "Wilhelm van Astrea", universe: "Re:Zero", tier: "T14 - City Level" },
  { id: 448, name: "Julius Juukulius", universe: "Re:Zero", tier: "T12 - Continent Level" },
  { id: 449, name: "Elsa Granhiert", universe: "Re:Zero", tier: "T10 - Planetary" },
  { id: 450, name: "Regulus Corneas", universe: "Re:Zero", tier: "T7 - Universal" },
  { id: 451, name: "Satella (Witch of Envy)", universe: "Re:Zero", tier: "T3 - High Multiversal" },
  { id: 452, name: "Garfiel Tinsel", universe: "Re:Zero", tier: "T15 - Mountain Level" },
  { id: 453, name: "Ley Batenkaitos", universe: "Re:Zero", tier: "T16 - Building Level" },
  { id: 454, name: "Anastasia Hoshin", universe: "Re:Zero", tier: "T18 - Street Level" },
  { id: 455, name: "Mitsurugi Kyouya", universe: "Re:Zero", tier: "T17 - Wall Level" },
  { id: 456, name: "Minerva Orland", universe: "Re:Zero", tier: "T10 - Planetary" },
  { id: 457, name: "Subaru Natsuki (Return by Death)", universe: "Re:Zero", tier: "T4 - Multiversal+" },
  { id: 458, name: "Al (Subaru's Inner Spirit)", universe: "Re:Zero", tier: "T14 - City Level" },
  { id: 459, name: "Echidna (Witch of Greed)", universe: "Re:Zero", tier: "T4 - Multiversal+" },
  { id: 460, name: "Capella Emerada Lugnica", universe: "Re:Zero", tier: "T13 - Country Level" },
  { id: 461, name: "Felt (Royal Candidate)", universe: "Re:Zero", tier: "T16 - Building Level" },
  { id: 462, name: "Patrasche", universe: "Re:Zero", tier: "T20 - Regular Human" },
  { id: 463, name: "Aurelion Sol", universe: "League of Legends", tier: "T3 - High Multiversal" },
  { id: 464, name: "Zoe", universe: "League of Legends", tier: "T4 - Multiversal+" },
  { id: 465, name: "Ornn", universe: "League of Legends", tier: "T8 - Large Planetary to Galaxy Level" },
  { id: 466, name: "Malphite", universe: "League of Legends", tier: "T9 - Star System Level" },
  { id: 467, name: "Bard", universe: "League of Legends", tier: "T5 - Multiversal" },
  { id: 468, name: "Taliyah", universe: "League of Legends", tier: "T10 - Planetary" },
  { id: 469, name: "Ivern", universe: "League of Legends", tier: "T13 - Country Level" },
  { id: 470, name: "Rakan", universe: "League of Legends", tier: "T14 - City Level" },
  { id: 471, name: "Xerath", universe: "League of Legends", tier: "T7 - Universal" },
  { id: 472, name: "Syndra", universe: "League of Legends", tier: "T6 - Universal+" },
  { id: 473, name: "LeBlanc", universe: "League of Legends", tier: "T11 - Moon Level" },
  { id: 474, name: "Ryze", universe: "League of Legends", tier: "T3 - High Multiversal" },
  { id: 475, name: "Swain", universe: "League of Legends", tier: "T14 - City Level" },
  { id: 476, name: "Karma", universe: "League of Legends", tier: "T10 - Planetary" },
  { id: 477, name: "Soraka", universe: "League of Legends", tier: "T12 - Continent Level" },
  { id: 478, name: "Zilean", universe: "League of Legends", tier: "T8 - Large Planetary to Galaxy Level" },
  { id: 479, name: "Senna", universe: "League of Legends", tier: "T13 - Country Level" },
  { id: 480, name: "Lucian", universe: "League of Legends", tier: "T15 - Mountain Level" },
  { id: 481, name: "Jhin", universe: "League of Legends", tier: "T18 - Street Level" },
  { id: 482, name: "Ezreal", universe: "League of Legends", tier: "T13 - Country Level" },
  { id: 483, name: "Teemo", universe: "League of Legends", tier: "T19 - Peak Human" },
  { id: 484, name: "Yasuo", universe: "League of Legends", tier: "T14 - City Level" },
  { id: 485, name: "Riven", universe: "League of Legends", tier: "T15 - Mountain Level" },
  { id: 486, name: "Tryndamere", universe: "League of Legends", tier: "T15 - Mountain Level" },
  { id: 487, name: "Darius", universe: "League of Legends", tier: "T12 - Continent Level" },
  { id: 488, name: "Garen", universe: "League of Legends", tier: "T12 - Continent Level" },
  { id: 489, name: "Katarina", universe: "League of Legends", tier: "T15 - Mountain Level" },
  { id: 490, name: "Kennen", universe: "League of Legends", tier: "T14 - City Level" },
  { id: 491, name: "Irelia", universe: "League of Legends", tier: "T14 - City Level" },
  { id: 492, name: "Akali", universe: "League of Legends", tier: "T14 - City Level" },
  { id: 493, name: "Ahri", universe: "League of Legends", tier: "T11 - Moon Level" },
  { id: 494, name: "Annie", universe: "League of Legends", tier: "T18 - Street Level" },
  { id: 495, name: "Brand", universe: "League of Legends", tier: "T13 - Country Level" },
  { id: 496, name: "Kog'Maw", universe: "League of Legends", tier: "T20 - Regular Human" },
  { id: 497, name: "Sion", universe: "League of Legends", tier: "T13 - Country Level" },
  { id: 498, name: "Thresh", universe: "League of Legends", tier: "T12 - Continent Level" },
  { id: 499, name: "Vayne", universe: "League of Legends", tier: "T18 - Street Level" },
  { id: 500, name: "Jinx", universe: "League of Legends", tier: "T19 - Peak Human" },
  { id: 501, name: "Vi", universe: "League of Legends", tier: "T16 - Building Level" },
  { id: 502, name: "Caitlyn", universe: "League of Legends", tier: "T17 - Wall Level" },
  { id: 503, name: "Ashe", universe: "League of Legends", tier: "T17 - Wall Level" },
  { id: 504, name: "Lux", universe: "League of Legends", tier: "T11 - Moon Level" },
  { id: 505, name: "Morgana", universe: "League of Legends", tier: "T13 - Country Level" },
  { id: 506, name: "Leona", universe: "League of Legends", tier: "T12 - Continent Level" },
  { id: 507, name: "Nami", universe: "League of Legends", tier: "T17 - Wall Level" },
  { id: 508, name: "Thresh", universe: "League of Legends", tier: "T12 - Continent Level" },
  { id: 509, name: "Fiora", universe: "League of Legends", tier: "T16 - Building Level" },
  { id: 510, name: "Zed", universe: "League of Legends", tier: "T14 - City Level" },
  { id: 511, name: "Ekko", universe: "League of Legends", tier: "T13 - Country Level" },
  { id: 512, name: "Shen", universe: "League of Legends", tier: "T14 - City Level" },
  { id: 513, name: "Lee Sin", universe: "League of Legends", tier: "T15 - Mountain Level" },
  { id: 514, name: "Master Yi", universe: "League of Legends", tier: "T14 - City Level" },
  { id: 515, name: "Rengar", universe: "League of Legends", tier: "T17 - Wall Level" },
  { id: 516, name: "Kha'Zix", universe: "League of Legends", tier: "T16 - Building Level" },
  { id: 517, name: "Rek'Sai", universe: "League of Legends", tier: "T18 - Street Level" },
  { id: 518, name: "Nidalee", universe: "League of Legends", tier: "T15 - Mountain Level" },
  { id: 519, name: "Elise", universe: "League of Legends", tier: "T13 - Country Level" },
  { id: 520, name: "Camille", universe: "League of Legends", tier: "T14 - City Level" },
  { id: 521, name: "Viktor", universe: "League of Legends", tier: "T13 - Country Level" },
  { id: 522, name: "Swain", universe: "League of Legends", tier: "T14 - City Level" },
  { id: 523, name: "Galio", universe: "League of Legends", tier: "T8 - Large Planetary to Galaxy Level" },
  { id: 524, name: "Rumble", universe: "League of Legends", tier: "T17 - Wall Level" },
  { id: 525, name: "Heimerdinger", universe: "League of Legends", tier: "T16 - Building Level" },
  { id: 526, name: "Ziggs", universe: "League of Legends", tier: "T13 - Country Level" },
  { id: 527, name: "Janna", universe: "League of Legends", tier: "T14 - City Level" },
  { id: 528, name: "Sona", universe: "League of Legends", tier: "T12 - Continent Level" },
  { id: 529, name: "Seraphine", universe: "League of Legends", tier: "T11 - Moon Level" },
  { id: 530, name: "Kai'Sa", universe: "League of Legends", tier: "T15 - Mountain Level" },
  { id: 531, name: "Xayah", universe: "League of Legends", tier: "T16 - Building Level" },
  { id: 532, name: "Rakan", universe: "League of Legends", tier: "T14 - City Level" },
  { id: 533, name: "Thresh", universe: "League of Legends", tier: "T12 - Continent Level" },
  { id: 534, name: "Yasuo", universe: "League of Legends", tier: "T14 - City Level" },
  { id: 535, name: "Yone", universe: "League of Legends", tier: "T14 - City Level" },
  { id: 536, name: "Senna", universe: "League of Legends", tier: "T13 - Country Level" },
  { id: 537, name: "Lucian", universe: "League of Legends", tier: "T15 - Mountain Level" },
  { id: 538, name: "Aphelios", universe: "League of Legends", tier: "T16 - Building Level" },
  { id: 539, name: "Viego", universe: "League of Legends", tier: "T10 - Planetary" },
  { id: 540, name: "Samira", universe: "League of Legends", tier: "T18 - Street Level" },
  { id: 541, name: "Rell", universe: "League of Legends", tier: "T14 - City Level" },
  { id: 542, name: "Kayn", universe: "League of Legends", tier: "T13 - Country Level" },
  { id: 543, name: "Lillia", universe: "League of Legends", tier: "T13 - Country Level" },
  { id: 544, name: "Sett", universe: "League of Legends", tier: "T15 - Mountain Level" },
  { id: 545, name: "Neeko", universe: "League of Legends", tier: "T17 - Wall Level" },
  { id: 546, name: "Sylas", universe: "League of Legends", tier: "T14 - City Level" },
  { id: 547, name: "Zeri", universe: "League of Legends", tier: "T16 - Building Level" },
  { id: 548, name: "Gwen", universe: "League of Legends", tier: "T14 - City Level" },
  { id: 549, name: "Qiyana", universe: "League of Legends", tier: "T14 - City Level" },
  { id: 550, name: "Akshan", universe: "League of Legends", tier: "T15 - Mountain Level" },
  
];

export default function Home() {
  const [selectedTier, setSelectedTier] = useState(tiers[0]);

  const filtered = characters.filter(c => c.tier === selectedTier);

  return (
    <div style={{ padding: "1rem", fontFamily: "Arial, sans-serif" }}>
      <h1>All Tier List</h1>
      <div style={{ marginBottom: "1rem" }}>
        {tiers.map(tier => (
          <button
            key={tier}
            onClick={() => setSelectedTier(tier)}
            style={{
              marginRight: "0.5rem",
              padding: "0.5rem 1rem",
              background: selectedTier === tier ? "#222" : "#eee",
              color: selectedTier === tier ? "#fff" : "#000",
              border: "none",
              borderRadius: "4px",
              cursor: "pointer"
            }}
          >
            {tier}
          </button>
        ))}
      </div>

      <h2>{selectedTier} Tier Characters</h2>
      <ul>
        {filtered.map(c => (
          <li key={c.id}>
            <strong>{c.name}</strong> - {c.universe}
          </li>
        ))}
        {filtered.length === 0 && <li>No characters in this tier.</li>}
      </ul>
    </div>
  );
}
